--gamestate_init_lua
texturePath = "data/texture/animationtest.png"
local texture = asManager:createTexture("mainTexture")
assert(texture:loadFromFile(texturePath, IntRect.new()), "Error texture load")
local walkingAnimationDown = asManager:createAnimation("walkingAnimationDown")
walkingAnimationDown:setSpriteSheet(texture)
walkingAnimationDown:addFrame(IntRect.new(32, 0, 32, 32))
walkingAnimationDown:addFrame(IntRect.new(64, 0, 32, 32))
walkingAnimationDown:addFrame(IntRect.new(32, 0, 32, 32))
walkingAnimationDown:addFrame(IntRect.new( 0, 0, 32, 32))
local walkingAnimationLeft = asManager:createAnimation("walkingAnimationLeft")
walkingAnimationLeft:setSpriteSheet(texture)
walkingAnimationLeft:addFrame(IntRect.new(32, 32, 32, 32))
walkingAnimationLeft:addFrame(IntRect.new(64, 32, 32, 32))
walkingAnimationLeft:addFrame(IntRect.new(32, 32, 32, 32))
walkingAnimationLeft:addFrame(IntRect.new( 0, 32, 32, 32))
local walkingAnimationRight = asManager:createAnimation("walkingAnimationRight")
walkingAnimationRight:setSpriteSheet(texture)
walkingAnimationRight:addFrame(IntRect.new(32, 64, 32, 32))
walkingAnimationRight:addFrame(IntRect.new(64, 64, 32, 32))
walkingAnimationRight:addFrame(IntRect.new(32, 64, 32, 32))
walkingAnimationRight:addFrame(IntRect.new( 0, 64, 32, 32))
local walkingAnimationUp = asManager:createAnimation("walkingAnimationUp")
walkingAnimationUp:setSpriteSheet(texture)
walkingAnimationUp:addFrame(IntRect.new(32, 96, 32, 32))
walkingAnimationUp:addFrame(IntRect.new(64, 96, 32, 32))
walkingAnimationUp:addFrame(IntRect.new(32, 96, 32, 32))
walkingAnimationUp:addFrame(IntRect.new( 0, 96, 32, 32))
local mainObj = oManager:createDynamicGameObject()
player:setObject(mainObj)
mainObj:addAnimation(walkingAnimationDown, aDown)
mainObj:addAnimation(walkingAnimationLeft, aLeft)
mainObj:addAnimation(walkingAnimationUp, aUp)
mainObj:addAnimation(walkingAnimationRight, aRight)
mainObj:setPosition(0, 0)
mainObj:setAnimation(aDown)
print "Hello"